### ISSUE TITLE
Directory structure when using supporting files

### ISSUE THREAD

**Issue by djhunter** [djhunter/webwork-open-problem-library#1]
When `zork.pg` uses `gork.png,` we have to put `zork.pg` and `gork.png` in a folder named `zork`. The reason for this is (I think) that when someone creates a new local copy of `zork.pg` using the problem editor, the WeBWorK system automatically copies the supporting files (`gork.png`). If `gork.png` were just sitting in some other directory, it wouldn't automatically be copied along with the local copy of the PG file.

**Comment by bstone** [comment]
Thanks. This makes sense. I like your filenames by the way.
